const usuariosDataInicial = [
  {
    id: 1,
    nombre: "Bulma",
    genero: "M",
    edad: 23,
    verificado: true,
    imagenPerfil: "profile-pics/bulma.jpg",
    imagenPortada: "cover-pics/bulma.jpg",
    ocupacion: "Cientifica",
    ciudad: "Tegucigalpa",
    intereses: ["Series", "Suchi", "Negocios"],
    matches: [2, 3],
    likes: [2, 3],
    generoInteres: ["F", "M"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 2,
    nombre: "Goku",
    genero: "M",
    edad: 23,
    verificado: true,
    imagenPerfil: "profile-pics/goku.jpg",
    imagenPortada: "cover-pics/goku.jpg",
    ocupacion: "Guerrero Z",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer"],
    matches: [3, 5],
    likes: [3, 5],
    generoInteres: ["F"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 3,
    nombre: "Gohan",
    genero: "M",
    edad: 23,
    verificado: false,
    imagenPerfil: "profile-pics/gohan.jpg",
    imagenPortada: "cover-pics/gohan.jpg",
    ocupacion: "Guerrero Z",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [2, 4],
    likes: [2, 4],
    generoInteres: ["F"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 4,
    nombre: "Hinata",
    genero: "M",
    edad: 23,
    verificado: true,
    imagenPerfil: "profile-pics/hinata.jpg",
    imagenPortada: "cover-pics/hinata.jpg",
    ocupacion: "Gening",
    ciudad: "Tegucigalpa",
    intereses: ["Jutsus", "Comer"],
    matches: [1, 2],
    likes: [1, 2],
    generoInteres: ["M"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 5,
    nombre: "Krillin",
    genero: "M",
    edad: 23,
    verificado: false,
    imagenPerfil: "profile-pics/krilin.jpg",
    imagenPortada: "cover-pics/krilin.jpg",
    ocupacion: "Humano",
    ciudad: "Tegucigalpa",
    intereses: ["Revistas", "Comer"],
    matches: [2, 3],
    likes: [2, 3],
    generoInteres: ["M"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 6,
    nombre: "Vegeta",
    genero: "M",
    edad: 23,
    verificado: true,
    imagenPerfil: "profile-pics/vegeta.jpg",
    imagenPortada: "cover-pics/vegeta.jpg",
    ocupacion: "Humano",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [2, 3],
    likes: [2, 3],
    generoInteres: ["M"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 7,
    nombre: "Videl",
    genero: "F",
    verificado: true,
    edad: 20,
    imagenPerfil: "profile-pics/videl.jpg",
    imagenPortada: "cover-pics/videl.jpg",
    ocupacion: "Guerrero Z",
    ciudad: "Tegucigalpa",
    intereses: ["Comer"],
    matches: [5],
    likes: [5],
    generoInteres: ["M"],
  },
  {
    id: 8,
    nombre: "Naruto",
    genero: "M",
    verificado: false,
    edad: 20,
    imagenPerfil: "profile-pics/naruto.jpg",
    imagenPortada: "cover-pics/naruto.jpg",
    ocupacion: "Hokage",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [7],
    likes: [7],
    generoInteres: ["F"],
  },
]
