const usuariosDataInicial = [
  {
    id: 1,
    nombre: "Bulma",
    genero: "M",
    verificado: true,
    imagenPerfil: "profile-pics/bulma.jpg",
    imagenPortada: "cover-pics/bulma.jpg",
    ocupacion: "Cientifica",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [2, 3],
    likes: [2, 3],
    generoInteres: ["F", "M"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 2,
    nombre: "Goku",
    genero: "M",
    verificado: true,
    imagenPerfil: "profile-pics/goku.jpg",
    imagenPortada: "cover-pics/gohan.jpg",
    ocupacion: "Guerrero Z",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [3, 5],
    likes: [3, 5],
    generoInteres: ["F"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 3,
    nombre: "Gohan",
    genero: "M",
    verificado: true,
    imagenPerfil: "profile-pics/gohan.jpg",
    imagenPortada: "cover-pics/gohan.jpg",
    ocupacion: "Guerrero Z",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [2, 4],
    likes: [2, 4],
    generoInteres: ["F"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 4,
    nombre: "Hinata",
    genero: "M",
    verificado: true,
    imagenPerfil: "profile-pics/hinata.jpg",
    imagenPortada: "cover-pics/hinata.jpg",
    ocupacion: "Gening",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [1, 2],
    likes: [1, 2],
    generoInteres: ["M"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 5,
    nombre: "Krillin",
    genero: "M",
    verificado: true,
    imagenPerfil: "profile-pics/krilin.jpg",
    imagenPortada: "cover-pics/krilin.jpg",
    ocupacion: "Humano",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [2, 3],
    likes: [2, 3],
    generoInteres: ["M"], // pueden estar ambos ['F', 'M']
  },
  {
    id: 6,
    nombre: "Vegeta",
    genero: "M",
    verificado: true,
    imagenPerfil: "profile-pics/vegeta.jpg",
    imagenPortada: "cover-pics/vegeta.jpg",
    ocupacion: "Humano",
    ciudad: "Tegucigalpa",
    intereses: ["Pelear", "Comer", "Genkidamas"],
    matches: [2, 3],
    likes: [2, 3],
    generoInteres: ["M"], // pueden estar ambos ['F', 'M']
  },
]
